<?php

namespace Lagdo\DbAdmin\Db\Driver\Facades\Traits;

use Lagdo\DbAdmin\Driver\Db\StatementInterface;
use Lagdo\DbAdmin\Driver\Entity\TableEntity;
use Lagdo\DbAdmin\Driver\Entity\TableFieldEntity;

use function array_filter;
use function array_keys;
use function array_map;
use function count;
use function implode;
use function is_numeric;
use function preg_match;
use function str_replace;

trait TableDumpTrait
{
    /**
     * The queries generated by the dump
     *
     * @var array
     */
    private $queries = [];

    /**
     * The dump options
     *
     * @var array
     */
    private $options;

    /**
     * Print CSV row
     *
     * @param array  $row
     *
     * @return void
     */
    private function dumpCsv(array $row)
    {
        // From functions.inc.php
        foreach ($row as $key => $val) {
            if (preg_match('~["\n,;\t]|^0|\.\d*0$~', $val ?? '') || $val === '') {
                $row[$key] = '"' . str_replace('"', '""', $val) . '"';
            }
        }
        $separator = match($this->options['format']) {
            'csv' => ',',
            'tsv' => "\t",
            default => ';',
        };
        $this->queries[] = implode($separator, $row);
    }

    /**
     * Convert a value to string
     *
     * @param mixed  $value
     * @param TableFieldEntity $field
     *
     * @return string
     */
    private function convertToString($value, TableFieldEntity $field): string
    {
        // From functions.inc.php
        if ($value === null) {
            return 'NULL';
        }

        if (!preg_match($this->driver->numberRegex(), $field->type) ||
            preg_match('~\[~', $field->fullType) && is_numeric($value)) {
            $value = $this->driver->quote(($value === false ? 0 : $value));
        }
        return $this->driver->unconvertField($field, $value);
    }

    /**
     * @param string $table
     *
     * @return void
     */
    private function dumpTruncateQuery(string $table)
    {
        if ($this->options['format'] === 'sql' &&
            $this->options['data_style'] === 'TRUNCATE+INSERT') {
            $this->queries[] = $this->driver->getTruncateTableQuery($table) . ";\n";
        }
    }

    /**
     * @param DataDump $dump
     * @param array $row
     * @param StatementInterface $statement
     *
     * @return array
     */
    private function getDataRowKeys(DataDump $dump, array $row, StatementInterface $statement): array
    {
        $values = [];
        $keys = [];
        // For is preferred to foreach because the values are not used.
        // foreach ($row as $val) {
        // }
        $rowCount = count($row);
        for ($i = 0; $i < $rowCount; $i++) {
            $field = $statement->fetchField();
            $keys[] = $field->name();
            $key = $this->driver->escapeId($field->name());
            $values[] = "$key = VALUES($key)";
        }
        $dump->suffix = $this->options['data_style'] !== 'INSERT+UPDATE' ? ';' :
            "\nON DUPLICATE KEY UPDATE " . implode(', ', $values) . ';';

        return $keys;
    }

    /**
     * @param DataDump $dump
     * @param array $fields
     * @param array $row
     * @param array $keys
     *
     * @return void
     */
    private function dumpRow(DataDump $dump, array $fields, array $row, array $keys)
    {
        if ($this->options['format'] !== 'sql') {
            if ($this->options['data_style'] === 'table') {
                $this->dumpCsv($keys);
                $this->options['data_style'] = 'INSERT';
            }
            $this->dumpCsv($row);
            return;
        }

        if ($dump->insert === '') {
            $dump->insert = 'INSERT INTO ' . $this->driver->escapeTableName($dump->table) . ' (' .
                implode(', ', array_map(function ($key) {
                    return $this->driver->escapeId($key);
                }, $keys)) . ') VALUES';
        }
        foreach ($row as $key => $val) {
            $field = $fields[$key];
            $row[$key] = $this->convertToString($val, $field);
        }

        $dump->addRow($row);
        if ($dump->limitExceeded()) {
            $this->queries[] = $dump->makeQuery();
        }
    }

    /**
     * @param DataDump $dump
     * @param StatementInterface $statement
     *
     * @return void
     */
    private function dumpRows(DataDump $dump, StatementInterface $statement)
    {
        $fields = $this->options['format'] !== 'sql' ? [] : $this->driver->fields($dump->table);
        $keys = [];
        $fetchFunction = $dump->table !== '' ?
            fn($statement) => $statement->fetchAssoc() :
            fn($statement) => $statement->fetchRow();
        while ($row = $fetchFunction($statement)) {
            if (empty($keys)) {
                $keys = $this->getDataRowKeys($dump, $row, $statement);
            }
            $this->dumpRow($dump, $fields, $row, $keys);
        }
        if (count($dump->dataRows) > 0) {
            $this->queries[] = $dump->makeQuery();
        }
    }

    /** Export table data
     *
     * @param string $table
     *
     * @return void
     */
    private function dumpTableData(string $table)
    {
        if (!$this->options['data_style']) {
            return;
        }
        $fields = $this->driver->fields($table);
        $query = 'SELECT *' . $this->driver->convertFields($fields, $fields) .
            ' FROM ' . $this->driver->escapeTableName($table);
        // 1 - MYSQLI_USE_RESULT //! enum and set as numbers
        $statement = $this->driver->execute($query);
        if (!$statement) {
            if ($this->options['format'] === 'sql') {
                $this->queries[] = '-- ' . str_replace("\n", ' ', $this->driver->error()) . "\n";
            }
            return;
        }

        $maxRowSize = ($this->driver->jush() === 'sqlite' ? 0 : 1048576); // default, minimum is 1024
        $separator = $maxRowSize > 0 ? "\n" : ' ';
        $dump = new DataDump($table, $maxRowSize, $separator);

        $this->dumpTruncateQuery($table);
        $this->dumpRows($dump, $statement);
    }

    /**
     * @param string $table
     * @param string $style
     * @param int $tableType
     *
     * @return string
     */
    private function getCreateQuery(string $table, string $style, int $tableType): string
    {
        if ($tableType !== 2) {
            return $this->driver->getCreateTableQuery($table,
                $this->options['autoIncrement'], $style);
        }

        $fields = [];
        foreach ($this->driver->fields($table) as $name => $field) {
            $fields[] = $this->driver->escapeId($name) . ' ' . $field->fullType;
        }
        return 'CREATE TABLE ' . $this->driver->escapeTableName($table) .
            ' (' . implode(', ', $fields) . ')';
    }

    /**
     * Export table structure
     *
     * @param string $table
     * @param string $style
     * @param int    $tableType       0 table, 1 view, 2 temporary view table
     *
     * @return void
     */
    private function addCreateQuery(string $table, string $style, int $tableType): void
    {
        $query = $this->getCreateQuery($table, $style, $tableType);
        if (!$query) {
            return;
        }

        $this->driver->setUtf8mb4($query);
        if ($style === 'DROP+CREATE' || $tableType === 1) {
            $this->queries[] = 'DROP ' . ($tableType === 2 ? 'VIEW' : 'TABLE') .
                ' IF EXISTS ' . $this->driver->escapeTableName($table) . ';';
        }
        if ($tableType === 1) {
            $query = $this->driver->removeDefiner($query);
        }
        $this->queries[] = "$query;\n";
    }

    /**
     * Export table structure
     *
     * @param string $table
     * @param string $style
     * @param int    $tableType       0 table, 1 view, 2 temporary view table
     *
     * @return void
     */
    private function dumpCreateTableOrView(string $table, string $style, int $tableType = 0): void
    {
        // From adminer.inc.php
        if ($this->options['format'] !== 'sql') {
            $this->queries[] = "\xef\xbb\xbf"; // UTF-8 byte order mark
            if ($style) {
                $this->dumpCsv(array_keys($this->driver->fields($table)));
            }
            return;
        }
        if (!$style) {
            return;
        }

        $this->addCreateQuery($table, $style, $tableType);
    }

    /**
     * @param string $table
     *
     * @return void
     */
    private function dumpTableTriggers(string $table): void
    {
        if (($triggers = $this->driver->getCreateTriggerQuery($table)) !== '') {
            $this->queries[] = '';
            $this->queries[] = 'DELIMITER ;;';
            $this->queries[] = $triggers;
            $this->queries[] = 'DELIMITER ;';
        }
    }

    /**
     * @param TableEntity $tableStatus
     * @param bool $dumpTable
     * @param bool $dumpData
     *
     * @return void
     */
    private function dumpTable(TableEntity $tableStatus, bool $dumpTable, bool $dumpData): void
    {
        $style = $dumpTable ? $this->options['table_style'] : '';
        $tableType = $this->driver->isView($tableStatus) ? 2 : 1;
        $this->dumpCreateTableOrView($tableStatus->name, $style, $tableType);
        if ($dumpData) {
            $this->dumpTableData($tableStatus->name);
        }
        if ($this->options['to_sql'] && $this->options['triggers'] && $dumpTable) {
            $this->dumpTableTriggers($tableStatus->name);
        }
    }

    /**
     * @param array<TableEntity> $tableStatuses
     * @param array $tableOptions
     *
     * @return void
     */
    private function dumpTables(array $tableStatuses, array $tableOptions): void
    {
        foreach ($tableStatuses as $status) {
            $this->queries[] = '';
            $options = $tableOptions[$status->name] ?? $tableOptions['*'];
            $this->dumpTable($status, $options['table'], $options['data']);
        }
        if ($this->driver->jush() !== 'pgsql') {
            return;
        }

        // Add FKs after creating tables (except in MySQL which uses SET FOREIGN_KEY_CHECKS=0)
        $this->queries[] = '';
        $tables = array_filter($tableStatuses,
            fn($status) => !$this->driver->isView($status));
        foreach ($tables as $status) {
            $queries = $this->driver->getForeignKeysQueries($status);
            foreach ($queries as $query) {
                $this->queries[] = $query;
            }
            if (count($queries) > 0) {
                $this->queries[] = '';
            }
        }
    }

    /**
     * @param array $tableStatuses
     *
     * @return void
     */
    private function dumpViews(array $tableStatuses)
    {
        $views = array_filter($tableStatuses,
            fn($status) => $this->driver->isView($status));
        foreach ($views as $view) {
            $this->dumpCreateTableOrView($view->name, $this->options['table_style'], 1);
        }
    }
}
